### PR TITLE
changed to support multiple generators

### PR DESCRIPTION
**Pull request by roger-castaldo**
Attempt number 2 to support multiple qrcode generators.  Had to patch the SkiaSharp.QRCode library to generate a more testable qrcode based on the QRCoder code base for filling in the empty spots with white.  Created a new set of automated tests to ensure that it can generate valid QRCodes with either the QRCoder library or the SkiaSharp.QRCode Library.  The purpose of introducing this dynamic concept is to allow this library to run on a linux box as support for the System.Drawing.Common is being disabled in Linux, and the suggestion is to move to SkiaSharp.  With this concept in mind, this library should not support multiple operating systems and the user simply needs to include the reference to the right nuget package in their software.

### CODE REVIEW

**Comment by ahwm** [comment]
@flytzen @BrandonPotter thoughts? Only real issue with this is we would be incrementing the major version and .NET 4.5.2 is out of support as of today so if we're going to drop 4.5 (which we should do eventually, anyway) then we should swap it for at least 4.6.2 instead as per https://dotnet.microsoft.com/en-us/download/dotnet-framework

There's been some discussion in #89 around the idea of multiple QR Code providers. Where do you see this fitting in with that? On one hand, it is decoupled. So the developer would have to *know* that they need to add an additional reference to either `QRCoder` or `SkiaSharp.QrCode` which breaks the "just works" mantra a little bit.

**Comment by flytzen** [comment]
I prefer that we make it "just work". If we need two different QR libraries for that to work, we should handle that by referencing the appropriate package conditionally. 
I would personally prefer if we can make it work on all platforms with just a single QR library. I think means moving up to netstandard 2.0 (or something similar) as a minimum version and dropping explicit support for Framework altogether.
Personally, I feel that is the best way to go and upgrade to 3.0 in the process. It's not like we are adding features anyway, so anyone still on an old version of Framework that can't consume netstandard will have to stick with 2.x.
Moving to 3 would also allow us to tidy up other things, like the encode issue.

Thoughts?

**Comment by ahwm** [comment]
My only issue with using netstandard is all the problems with it in various .NET applications (see https://github.com/dotnet/standard/issues/542) so I personally prefer to target .NET Framework and .NET 3.1+ separately in my personal projects.

That being said, I'm completely fine with changing to target only `netstandard2.0` (as guidance in https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/)

I also like the idea of only having one dependency. And if we only use the `PngByteQRCode` class reference from QRCoder I don't see any problem continuing to use that library as long as it works on all platforms.

**Comment by roger-castaldo** [comment]
I understand there is a debate here for what to do next, but I would like to point out that using this means your library will support multiple versions of dotnet, running on any operating system, as long as the programmer using it has referenced the appropriate qrcode generator.  The only reason I thought to implement this, was the library at https://github.com/roger-castaldo/BPMEngine that I am the primary author of, generates images.  Initially I used System.Drawing.Common and then microsoft pulled support for that on certain OSes, so I built wrappers to handle things as long as you have either referenced the  System.Drawing.Common package or the SkiaSharp package in the nuget list.  This allowed this library to run on any system, without caring.  The only caveat is that it is unable to draw if you brought in neither library.  The same would occur here, the authentication aspects still work without error, it would only error out if the person using this package neglected to import a QRCode library and attempted to create a QRCode.

**Comment by flytzen** [comment]
@roger-castaldo That looks like a great library 👍 
I think the users are likely to be different, hence why I think the experience for GoogleAuthenticator probably needs to be a bit different.
Assuming we have to choose one provider for GoggleAuthenticator, can I ask what made you choose Skia specifically? Also, do you happen to know if the `PngByteQRCode` completely bypasses `System.Drawing` or is there some other magic that makes it work?

**Comment by roger-castaldo** [comment]
It's a bit of a long story but here it goes:
As part of microsoft's sunsetting of Drawing on non-windows OSes they listed 3 alternatives (MAUI, SkiaSharp and I forget the third).  MAUI is still in beta area, though I tried it and had issues.  The other one that I forget, same things.  SkiaSharp runs on any platform, supports multiple versions of dotnet, is quite mature, and what sealed the deal for me was the fact that the differences (methods, class names, etc) are negligible making wrappers much easier to write.

The PngByteCode looks like it bypasses System.Drawing at least from my quick glance over of the code, however, how it works is it looks like its literally writing out the binary equivalent of the image instead of using a drawing/rendering library to create it, which while it works, I personally am not a fan of doing things that way.  Also it looks like your code only uses that for dotnet6, is that because that method is only supported in that version or would it run in say core and previous versions just fine.

**Comment by ahwm** [comment]
@roger-castaldo It doesn't use imaging at all but hardcoded `byte[]` values to build a QR Code, as you pointed out. Guarding it to only .NET 6 was initially because .NET 6 was the framework that wasn't working and we wanted to do some more testing before using it for everything (see #105 and https://github.com/BrandonPotter/GoogleAuthenticator/issues/69#issuecomment-1098257575)

**Comment by flytzen** [comment]
@roger-castaldo Okay, one more question.
> The PngByteCode looks like it bypasses System.Drawing at least from my quick glance over of the code, however, how it works is it looks like its literally writing out the binary equivalent of the image instead of using a drawing/rendering library to create it, which while it works, I personally am not a fan of doing things that way.

What makes you not a fan of doing it that way? To me it looks pretty good - if anything it should perform better, I would imagine.

**Comment by roger-castaldo** [comment]
perform better, potentially, I have just never been a fan of doing thing "by hand" like that when there are libraries around that are built to do that.  I have had some bad experiences in my past of doing such things, and while they worked, they eventually became problematic, but thankfully other libraries had caught up by then that could handle those parts.  If the consensus is to not integrate my proposed changes, I will take no offense on it, though I may deploy my own nuget with those changes (tagged differently of course and with link backs to this library) as well as try and maintain things by integrating from this master as things progress, as long as there is no quams about me doing that.

**Comment by flytzen** [comment]
> perform better, potentially, I have just never been a fan of doing thing "by hand" like that when there are libraries around that are built to do that. I have had some bad experiences in my past of doing such things, and while they worked, they eventually became problematic, but thankfully other libraries had caught up by then that could handle those parts. If the consensus is to not integrate my proposed changes, I will take no offense on it, though I may deploy my own nuget with those changes (tagged differently of course and with link backs to this library) as well as try and maintain things by integrating from this master as things progress, as long as there is no quams about me doing that.

Thank you, that is very helpful. I think I will prefer to go with `PngByteCode` as it looks like it will work transparently across all frameworks. Not only my decision, though :)
Of course feel free to fork it :) Just wondering why, if there is no difference in the end-user experience and it's just a different underlying implementation with no impact on how it is used, where it can be used or how it performs? Please don't take that the wrong way, I think it is great what you are doing and have absolutely no problem with you taking it in a different direction.

**Comment by ahwm** [comment]
> @ahwm @BrandonPotter Okay, so here is my vote: We stick with `PngByteQRCode` as it should work transparently across all .Net frameworks and operating systems. We may still want to bump it to v3 as it's big change and we'll want to go from Framework 4.5 to 4.5.2 and we may want to address the Url encoding thing, which is potentially a breaking change.
> 
> What do you think @ahwm?

+1 for bump to v3.

I'm on the fence with the 4.5.2 support. 4.5.2 reached EOL a few days ago.  On one hand there will still be a lot of projects that target that, but then they could use 2.x or 1.x in that case with no real issue. So I feel like with 3.x we should potentially bump to 4.6.2. I'm leaning toward `net462`, `netcoreapp3.1`, `net5.0`, `net6.0` to cover the current LTS releases, but if 4.5.2 is preferred over 4.6.2 that's fine for now.

Changing to `netstandard2.0` as the target already bumps the compatibility to 4.6.1 (or potentially 4.7.2) and newer (as per https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0)

> The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

image

**Comment by flytzen** [comment]
@roger-castaldo Thank you for your work on this. As you may have gleaned, we decided to go another way and avoid the need for developers to have to choose a 3rd party lib. We have tested that functionality and it works so we are going with that. 
I am therefore going to close this PR, but wanted to say thank you for your input: You certainly helped to crystallise our thoughts and spur us into action.

**Pull request closed without merging**
