### PR TITLE
removing unused accountSecretKey field

### LINKED ISSUE #45: SetupCode has redundant property
Looks like as of V2 the `AccountSecretKey` is no longer used or populated so should be removed.

### PR DESCRIPTION
**Pull request by ahwm**
This also bumps the nuget package version to 2.0.1

fixes #45

### CODE REVIEW

**Comment by dfibuch** [comment]
Well that was quick. There you go @flytzen

Cheers @ahwm

**Comment by ahwm** [comment]
@flytzen It doesn't seem to be building this PR. Any ideas on what's going on?

**Comment by dfibuch** [comment]
Looks like it is still building @ahwm though I don't have access to the pipeline so can't see what its doing there.

**Comment by ahwm** [comment]
Azure DevOps doesn't appear to have been triggered.

**Comment by flytzen** [comment]
@ahwm let me check

**Pull request merged**
