### PR TITLE
Allow configuration of TimeStep

### LINKED ISSUE #206: Allow varying window sizes
Currently this library is (I believe) hard coded to 30 second intervals. The TOTP standard allows for other intervals, 

Would you consider adding options for 60 seconds?

### PR DESCRIPTION
**Pull request by flytzen**
- Added support for specifying the timestep in config
- Updated version and readme

Fixes #206

### CODE REVIEW

**Review by ahwm — APPROVED** [review]

**Comment by asmith3006** [comment]
Thank you! Amazing.

**Comment by flytzen** [comment]
@asmith3006 we don't really have a way to test this... We'll publish it as a beta - when we do, can you test it with your devices and let us know if we can release this?
Thanks 😊

**Comment by asmith3006** [comment]
Have run this code on a mock console app and tested against a known secret on a physical token and it's working perfectly. 

FYI you can also use https://totp.danhersam.com/ to test against a known secret and change the window size for comparison. 

Thanks for this! Great work.

**Comment by ahwm** [comment]
That's about as much as we can do with the tests (and is pretty much what the tests check). Let us know once you're able to test it with a real device as well. Glad to hear it's on the right track!

**Comment by asmith3006** [comment]
I've compared the output with:

1. Physical token
2. Online generator
3. Powershell script

and all numbers generated by all the systems match perfectly. 

I think that's about all the testing I can do, it looks great - thank you!

**Pull request merged**
