### PR TITLE
Netstandard

### PR DESCRIPTION
**Pull request by flytzen**

### CODE REVIEW

**Comment by flytzen** [comment]
@BrandonPotter 
- The Azure build pipeline is now working. The repo still tries to run AppVeyor as well - I don't have the power to remove that.
- I would suggest you change the settings for the repo to require the CI to pass before the PR can be merged - again, I don't have the power :)

I'd like to merge this to master now to finish adding build badges etc. @ahwm - do you agree that we should go ahead or should we wait for @BrandonPotter?

**Comment by ahwm** [comment]
@flytzen I'd say go ahead and add the badges

**Comment by BrandonPotter** [comment]
Disabled appveyor hooks!

**Comment by BrandonPotter** [comment]
Branch check rule added for `master` as well

**Comment by flytzen** [comment]
> Branch check rule added for `master` as well

@BrandonPotter In the settings you mean? Not sure you need that as that is specified in the yaml file. But it won't hurt :)

**Comment by ahwm** [comment]
> > Branch check rule added for `master` as well
> 
> @BrandonPotter In the settings you mean? Not sure you need that as that is specified in the yaml file. But it won't hurt :)

The branch check will disallow merging unless all checks complete and at least one reviewer approves the changes. By default you can still merge a pull request even if build checks don't pass.

**Pull request merged**
