### PR TITLE
Support for dotnetcore

### PR DESCRIPTION
**Pull request by andyedinborough**
Converted to use xunit.  Code changes were minimal.

### CODE REVIEW

**Comment by BrandonPotter** [comment]
CI build failing (appveyor), will be a bit before I can check why

**Comment by andyedinborough** [comment]
Yeah, it doesn't surprise me.  The build process will need some updates also.

**Comment by andyedinborough** [comment]
Looks like it needs a `dotnet restore` run before build.  I'm not familiar with AppVeyor, but you should be able to just run `dotnet publish` to do everything.  That would even create the nuget package if the nuspec file was in the source.

**Comment by BrandonPotter** [comment]
`dotnet restore` works - nuget package will auto publish on master commit, will the core change break existing non-core apps using the package? (Haven't played with core or this scenario since they started making major changes in beta)

**Comment by andyedinborough** [comment]
It depends on how the nuget packager is setup.  Running `dotnet publish` should create binaries for all the applicable frameworks.  I did have to set the framework to `netstandard1.3` which equates to .NET 4.6.  So the package should only be available to users running that version or higher.

**Comment by andrewlock** [comment]
Can I help get this moving at all? It looks like the CI build is passing - is it OK to merge?

One other thing - given the app previously supported .NET 4.5, it might be nice to cross compile the package for `net45` in addition to `netstandard1.3`, that way current users won't be affected by the upgrade.

**Comment by DOMZE** [comment]
Can't wait for this!

Have you guys found a dotnetcore compatible QRCode generator? QRCoder is full on .NET3.5/4.0

**Comment by revinfotech2** [comment]
Well I am getting the issue at the dedicated server. And also things are going good at AWS server.

**Comment by ahwm** [comment]
I've just added a new pull request that uses the modern .NET Standard. The latest version of QRCoder requires netstandard1.6 or newer. Also, the global.json, etc is now obsolete.

I set it to multi-target netstandard2.0 and net45.

**Comment by ahwm** [comment]
Closing due to #29

**Pull request closed without merging**
