### PR TITLE
Replace Deprecated Charts API

### PR DESCRIPTION
**Pull request by ahwm**
Google has deprecated the charts API and, as a result, this library may become unusable as the QR functionality may stop working at any time.

Unfortunately, this solution eliminates the single library option at this time.

Reference: https://developers.google.com/chart/infographics/docs/qr_codes

### CODE REVIEW

**Comment by ahwm** [comment]
Would resolve #4 by generating the QR image locally.

**Comment by ahwm** [comment]
Any feedback @BrandonPotter ?

**Comment by mjwills** [comment]
Can this be merged in @BrandonPotter ? The charts API is now dead, rather than just deprecated.

**Comment by robinvdbroek** [comment]
Hi @BrandonPotter any chance that you could release a new NuGet package containing the fix?

**Comment by haligasd** [comment]
Yes please @BrandonPotter  we need the nuget as well.  thanks

**Pull request merged**
