### PR TITLE
.NET Standard

### PR DESCRIPTION
**Pull request by ahwm**
This updates the VS version required and multi-targets .NET Standard 2.0 and .NET 4.6.2.

This would address #15 

We will be using this library in a .NET Core application and, while the full framework version does work, it gives warnings about it not being totally compatible.

### CODE REVIEW

**Comment by ahwm** [comment]
With a few tweaks to appveyor, this build does work: https://ci.appveyor.com/project/ahwm/googleauthenticator

**Comment by davidpeden3** [comment]
@BrandonPotter are you still supporting this repo/package?

@ahwm are you still working on this? your fork hasn't moved since this pr.

**Comment by ahwm** [comment]
@davidpeden3 My fork is as I use it in production. I haven't had a need to make any changes since this PR. :)

**Comment by ahwm** [comment]
@BrandonPotter Any other feedback on this? I'd be happy to help out more if I got permissions on GitHub and nuget.

**Comment by flytzen** [comment]
@ahwm If @BrandonPotter has abandoned this, it may be time to work from your fork and publish it? I think the name of the package could change as it's generic TOTP and not specific to Google anyway, hence solving the problem of freeing up the name on Nuget?
I'd be happy to lend a hand; in particular with setting up the build pipeline to auto-publish to Nuget etc if you want?

/cc @dfibuch

**Comment by ahwm** [comment]
@flytzen I don't think he has totally abandoned it - https://github.com/BrandonPotter/GoogleAuthenticator/issues/15#issuecomment-561912140

I just think he needs some help. :)

**Comment by flytzen** [comment]
@ahwm Ah, hadn't seen that. Sorry @BrandonPotter :)

**Comment by flytzen** [comment]
@ahwm FYI: I am merging this into another branch in the repo as it's easier to use `dotnet` than ms build, which means I need to modify the csproj files etc.

**Comment by ahwm** [comment]
@flytzen sounds good.

**Comment by flytzen** [comment]
@ahwm @BrandonPotter I'm trying to run the one unit test in both master and in ahwm's branch and it just dies with an out of memory exception. Looking at the test, I am not sure it ever worked? 
I am going to comment it out for now and just put a dummy test in for the build chain to use. Let me know if this does not match with you experience.

**Pull request merged**
